# -*- mode: ruby -*-
# vi: set ft=ruby :

# ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

        # Hello server
        config.vm.define "hello" do |node|

            node.vm.box               = "generic/ubuntu2004"
            node.vm.box_check_update  = false
            node.vm.box_version       = "3.3.0"
            node.vm.hostname          = "hello.example.com"

            node.vm.network "private_network", ip: "192.168.56.9"

            node.vm.provider :virtualbox do |v|
                v.name    = "hello"
                v.memory  = 2048
                v.cpus    =  2
            end

            node.vm.provider :libvirt do |v|
                v.memory  = 2048
                v.nested  = true
                v.cpus    = 2
            end

        end

end